# for local development
version: '3.7'
services:
  frontend:
    build:
      context: .
      target: 'develop-stage'
    ports:
      - '80:8080'
    volumes:
      - '.:/app'
    command: /bin/sh -c "yarn serve"